import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { CharacterProvider } from "@/contexts/character.context";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pokemon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-mx">
      <body className={`${roboto.variable}  antialiased`}>{children}</body>
    </html>
  );
}
