import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { CharacterProvider } from "./contexts";

const roboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rick y Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es-mx">
      <body className={`${roboto.variable}  antialiased`}>
        <CharacterProvider>{children}</CharacterProvider>
      </body>
    </html>
  );
}
